Fix deprecated Django APIs in Django 1.10
Django 1.10 depracated django.core.urlresolvers
Change: from django.core.urlresolvers import reverse
into: from django.urls import reverse

Django 1.10: ForeignKey and OneToOneField require on_delete
parameter.

Django 1.10-2.0 changes model manager inheritance.
Django 1.10 enables new inheritance logic for managers in model
classes and it will be forced on in Django 2.0.

It looks like that inheriting model managers from the parent class
would not cause any issues (under class ModelWithInheritance).
However, something goes wrong in the BaseExercise class and it is
fixed by defining the default objects manager in the BaseExercise
class. The issue is that saving new model instances causes
a strange crash:
ValueError: Cannot force an update in save() with no primary key.
In the unit tests, this occurs in test_course_clone
(edit_course.tests.CourseCloneTest).

Django 1.10 user.is_authenticated and is_anonymous are now
properties.

Django 1.10 new-style MIDDLEWARE setting.
Additionally, remove the old Easter egg SQL injection middleware
(it was a bad joke).